interface Env{DB:D1Database;BUCKET:R2Bucket;ALLOWED_ORIGIN?:string}
type SessionUser={userId:string;accountId:string;workspaceId:string;username:string;displayName:string;email:string;role:string;mustChangePassword:boolean}
const ITERATIONS=150000,CATEGORIES=['Petição','Prova','Contrato','Outros'];
const DUMMY_SALT='YRwwwynU8equZ+NlM8WCjA==',DUMMY_HASH='/HPTQONGOQQe/+sRvLpxxMkUKWHDqxdDLyHX8BG0yt8=';

const allowedOrigin=(env:Env)=>env.ALLOWED_ORIGIN||'https://netosmith.github.io';
function cors(req:Request,env:Env){const h=new Headers({'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}),o=req.headers.get('origin');if(o&&o===allowedOrigin(env)){h.set('Access-Control-Allow-Origin',o);h.set('Vary','Origin');h.set('Access-Control-Allow-Headers','Authorization, Content-Type');h.set('Access-Control-Allow-Methods','GET,POST,DELETE,OPTIONS')}return h}
function out(req:Request,env:Env,data:unknown,status=200,extra?:HeadersInit){const h=cors(req,env);if(extra)new Headers(extra).forEach((v,k)=>h.set(k,v));h.set('Content-Type','application/json; charset=utf-8');return new Response(JSON.stringify(data),{status,headers:h})}
function fail(req:Request,env:Env,e:unknown){if(e instanceof Response){const h=cors(req,env);e.headers.forEach((v,k)=>h.set(k,v));return new Response(e.body,{status:e.status,headers:h})}console.error('Matos API',e);return out(req,env,{error:'Não foi possível concluir. Tente novamente.'},503)}
function bad(message:string,status=400):never{throw new Response(JSON.stringify({error:message}),{status,headers:{'Content-Type':'application/json'}})}
function checkOrigin(req:Request,env:Env){if(['GET','HEAD','OPTIONS'].includes(req.method))return;const o=req.headers.get('origin');if(!o||o!==allowedOrigin(env))bad('Origem não autorizada.',403)}
async function jsonBody(req:Request){const text=await req.text();if(text.length>250000)bad('Conteúdo muito grande.',413);try{return JSON.parse(text)}catch{bad('Dados inválidos.')}}
function normalizeUsername(v:string){return v.trim().toLowerCase().replace(/\s+/g,'')}
function toB64(bytes:Uint8Array){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s)}
function fromB64(v:string){const s=atob(v),a=new Uint8Array(s.length);for(let i=0;i<s.length;i++)a[i]=s.charCodeAt(i);return a}
function equal(a:Uint8Array,b:Uint8Array){if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a[i]^b[i];return d===0}
async function passwordHash(password:string,saltB64?:string,iterations=ITERATIONS){const salt=saltB64?fromB64(saltB64):crypto.getRandomValues(new Uint8Array(16)),key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']),bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt,iterations},key,256);return{hash:toB64(new Uint8Array(bits)),salt:toB64(salt),iterations}}
async function verifyPassword(password:string,salt:string,hash:string,iterations:number){const x=await passwordHash(password,salt,iterations);return equal(fromB64(x.hash),fromB64(hash))}
function randomToken(){const b=crypto.getRandomValues(new Uint8Array(32));return toB64(b).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
async function tokenHash(token:string){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token));return Array.from(new Uint8Array(d),b=>b.toString(16).padStart(2,'0')).join('')}
function bearer(req:Request){const v=req.headers.get('authorization')||'';return v.toLowerCase().startsWith('bearer ')?v.slice(7).trim():''}
async function currentUser(req:Request,env:Env):Promise<SessionUser>{const token=bearer(req);if(!token)bad('Sessão expirada. Entre novamente.',401);const id=await tokenHash(token),now=new Date().toISOString();const row:any=await env.DB.prepare(`SELECT u.id accountId,u.workspace_id workspaceId,u.username,u.display_name displayName,COALESCE(u.email,'') email,u.role,u.must_change_password mustChangePassword,w.data_owner dataOwner FROM sessions s JOIN users u ON u.id=s.user_id JOIN workspaces w ON w.id=u.workspace_id WHERE s.id=? AND s.expires>? AND u.active=1`).bind(id,now).first();if(!row)bad('Sessão expirada. Entre novamente.',401);return{userId:row.dataOwner,accountId:row.accountId,workspaceId:row.workspaceId,username:row.username,displayName:row.displayName,email:row.email||row.username,role:row.role,mustChangePassword:Boolean(row.mustChangePassword)}}
async function createSession(env:Env,userId:string,remember:boolean){const token=randomToken(),id=await tokenHash(token),now=new Date(),expires=new Date(now.getTime()+(remember?30:1)*86400000);await env.DB.batch([env.DB.prepare('DELETE FROM sessions WHERE expires<=?').bind(now.toISOString()),env.DB.prepare('INSERT INTO sessions (id,user_id,expires,created) VALUES (?,?,?,?)').bind(id,userId,expires.toISOString(),now.toISOString())]);return token}
async function audit(env:Env,owner:string,actor:string,action:string,detail:string){await env.DB.prepare('INSERT INTO activity (id,owner,actor,action,detail,created) VALUES (?,?,?,?,?,?)').bind(crypto.randomUUID(),owner,actor,action,detail,new Date().toISOString()).run()}
async function reference(env:Env,owner:string,id:string,kind:string){if(!id)return;const r=await env.DB.prepare('SELECT id FROM records WHERE owner=? AND id=? AND kind=?').bind(owner,id,kind).first();if(!r)bad('O vínculo selecionado não está disponível. Atualize a lista.')}
function validDate(v:any){return v===''||typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&!Number.isNaN(Date.parse(v))}
function validateRecord(kind:string,data:any){if(!['clients','processes','contracts'].includes(kind)||!data||typeof data!=='object')bad('Categoria inválida.');if(typeof data.name!=='string'||data.name.trim().length<2||data.name.length>300)bad('Confira os campos obrigatórios.');if(JSON.stringify(data).length>150000)bad('Registro muito grande.');if(kind!=='clients'&&!data.clientId)bad('Selecione o cliente.');if(kind==='processes'&&(!data.number||!validDate(data.deadline)))bad('Confira número e prazo do processo.');if(kind==='contracts'&&(!validDate(data.expires)||String(data.content||'').length>100000))bad('Confira os dados do contrato.')}

async function login(req:Request,env:Env){const b=await jsonBody(req),username=normalizeUsername(String(b.username||'')),password=String(b.password||''),remember=Boolean(b.remember);if(!/^[a-z0-9._-]{3,60}$/.test(username)||!password||password.length>128)bad('Informe usuário e senha.');const row:any=await env.DB.prepare('SELECT id,username,display_name,email,role,password_hash,password_salt,password_iterations,active,failed_attempts,locked_until,must_change_password,workspace_id FROM users WHERE username=? LIMIT 1').bind(username).first();if(!row){await verifyPassword(password,DUMMY_SALT,DUMMY_HASH,ITERATIONS);bad('Usuário ou senha inválidos.',401)}if(!row.active)bad('Usuário ou senha inválidos.',401);const now=new Date();if(row.locked_until&&new Date(row.locked_until)>now)bad('Acesso temporariamente bloqueado. Tente novamente em alguns minutos.',429);const ok=await verifyPassword(password,row.password_salt,row.password_hash,Number(row.password_iterations)||ITERATIONS);if(!ok){const tries=Number(row.failed_attempts||0)+1,lock=tries>=5?new Date(now.getTime()+15*60000).toISOString():null;await env.DB.prepare('UPDATE users SET failed_attempts=?,locked_until=?,updated=? WHERE id=?').bind(lock?0:tries,lock,now.toISOString(),row.id).run();bad(lock?'Muitas tentativas. Acesso bloqueado por 15 minutos.':'Usuário ou senha inválidos.',lock?429:401)}await env.DB.prepare('UPDATE users SET failed_attempts=0,locked_until=NULL,updated=? WHERE id=?').bind(now.toISOString(),row.id).run();const token=await createSession(env,row.id,remember);return out(req,env,{token,user:{username:row.username,displayName:row.display_name,email:row.email||row.username,role:row.role,mustChangePassword:Boolean(row.must_change_password)}})}
async function session(req:Request,env:Env){const u=await currentUser(req,env);return out(req,env,{user:{username:u.username,displayName:u.displayName,email:u.email,role:u.role,mustChangePassword:u.mustChangePassword}})}
async function changePassword(req:Request,env:Env){const u=await currentUser(req,env),b=await jsonBody(req),password=String(b.password||'');if(password.length<12||password.length>128||!/[A-Z]/.test(password)||!/[a-z]/.test(password)||!/\d/.test(password))bad('Use pelo menos 12 caracteres, com maiúscula, minúscula e número.');const p=await passwordHash(password),now=new Date().toISOString(),current=await tokenHash(bearer(req));await env.DB.batch([env.DB.prepare('UPDATE users SET password_hash=?,password_salt=?,password_iterations=?,must_change_password=0,updated=? WHERE id=?').bind(p.hash,p.salt,p.iterations,now,u.accountId),env.DB.prepare('DELETE FROM sessions WHERE user_id=? AND id<>?').bind(u.accountId,current)]);await audit(env,u.userId,u.displayName,'Senha alterada','Credencial de acesso atualizada');return out(req,env,{ok:true})}
async function logout(req:Request,env:Env){const token=bearer(req);if(token)await env.DB.prepare('DELETE FROM sessions WHERE id=?').bind(await tokenHash(token)).run();return out(req,env,{ok:true})}
async function recordsGet(req:Request,env:Env){const u=await currentUser(req,env),r=await env.DB.batch([env.DB.prepare('SELECT * FROM records WHERE owner=? ORDER BY updated DESC').bind(u.userId),env.DB.prepare('SELECT * FROM files WHERE owner=? ORDER BY created DESC').bind(u.userId),env.DB.prepare('SELECT * FROM activity WHERE owner=? ORDER BY created DESC LIMIT 80').bind(u.userId),env.DB.prepare('SELECT data FROM settings WHERE owner=?').bind(u.userId)]);return out(req,env,{records:r[0].results.map((v:any)=>({...v,data:JSON.parse(v.data),owner:undefined})),files:r[1].results.map((v:any)=>({...v,owner:undefined})),activity:r[2].results.map((v:any)=>({...v,owner:undefined})),settings:r[3].results[0]?JSON.parse((r[3].results[0] as any).data):null})}
async function recordsPost(req:Request,env:Env){const u=await currentUser(req,env),b=await jsonBody(req),kind=String(b.kind||''),data=b.data;validateRecord(kind,data);if(data.clientId)await reference(env,u.userId,data.clientId,'clients');if(data.processId)await reference(env,u.userId,data.processId,'processes');if(data.processId){const p:any=await env.DB.prepare('SELECT data FROM records WHERE owner=? AND id=?').bind(u.userId,data.processId).first();if(!p||JSON.parse(p.data).clientId!==data.clientId)bad('O processo deve pertencer ao cliente selecionado.')}const now=new Date().toISOString(),id=typeof b.id==='string'?b.id:crypto.randomUUID(),version=Number(b.version||0);if(b.id){const old:any=await env.DB.prepare('SELECT version FROM records WHERE id=? AND owner=? AND kind=?').bind(id,u.userId,kind).first();if(!old)return out(req,env,{error:'Registro não encontrado.'},404);if(old.version!==version)return out(req,env,{error:'Este registro foi alterado em outra sessão. Reabra o registro atualizado.'},409)}const statement=b.id?env.DB.prepare('UPDATE records SET data=?,version=version+1,updated=? WHERE id=? AND owner=? AND version=?').bind(JSON.stringify(data),now,id,u.userId,version):env.DB.prepare('INSERT INTO records (id,owner,kind,data,version,created,updated) VALUES (?,?,?,?,1,?,?)').bind(id,u.userId,kind,JSON.stringify(data),now,now);const result=await statement.run();if(!result.meta.changes)return out(req,env,{error:'Registro alterado em outra sessão. Reabra para editar.'},409);await audit(env,u.userId,u.displayName,b.id?'Registro atualizado':'Novo registro',data.name);return out(req,env,{id,version:b.id?version+1:1,updated:now})}
async function settingsPost(req:Request,env:Env){const u=await currentUser(req,env),b=await jsonBody(req);if(typeof b.name!=='string'||b.name.trim().length<2||b.name.length>300)bad('Confira os dados do escritório.');const data={name:String(b.name).trim(),oab:String(b.oab||'').slice(0,300),document:String(b.document||'').slice(0,300),address:String(b.address||'').slice(0,1000),email:String(b.email||'').slice(0,254),phone:String(b.phone||'').slice(0,300)};await env.DB.prepare('INSERT INTO settings (owner,data) VALUES (?,?) ON CONFLICT(owner) DO UPDATE SET data=excluded.data').bind(u.userId,JSON.stringify(data)).run();return out(req,env,{ok:true})}
async function filesPost(req:Request,env:Env,url:URL){const u=await currentUser(req,env),name=(url.searchParams.get('name')||'').replace(/[\r\n\\/]/g,'_').slice(0,220),category=url.searchParams.get('category')||'Outros',clientId=url.searchParams.get('clientId')||'',processId=url.searchParams.get('processId')||'',types:Record<string,string>={pdf:'application/pdf',docx:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',jpg:'image/jpeg',jpeg:'image/jpeg',png:'image/png'},mime=types[name.split('.').pop()?.toLowerCase()||''];if(!mime||!CATEGORIES.includes(category))bad('Use PDF, DOCX, JPG ou PNG e uma categoria válida.');await reference(env,u.userId,clientId,'clients');await reference(env,u.userId,processId,'processes');if(processId&&clientId){const p:any=await env.DB.prepare('SELECT data FROM records WHERE owner=? AND id=?').bind(u.userId,processId).first();if(!p||JSON.parse(p.data).clientId!==clientId)bad('O processo deve pertencer ao cliente.')}const bytes=await req.arrayBuffer();if(!bytes.byteLength||bytes.byteLength>50*1024*1024)bad('Envie um arquivo de até 50 MB.',413);const id=crypto.randomUUID(),key=u.userId+'/'+id,now=new Date().toISOString();await env.BUCKET.put(key,bytes,{httpMetadata:{contentType:mime}});try{await env.DB.prepare('INSERT INTO files (id,owner,name,category,client_id,process_id,size,mime,created) VALUES (?,?,?,?,?,?,?,?,?)').bind(id,u.userId,name,category,clientId,processId,bytes.byteLength,mime,now).run();await audit(env,u.userId,u.displayName,'Documento anexado',name)}catch(e){await env.BUCKET.delete(key);throw e}return out(req,env,{id})}
async function filesGet(req:Request,env:Env,url:URL){const u=await currentUser(req,env),id=url.searchParams.get('id')||'',f:any=await env.DB.prepare('SELECT * FROM files WHERE owner=? AND id=?').bind(u.userId,id).first();if(!f)return out(req,env,{error:'Arquivo não encontrado.'},404);const file=await env.BUCKET.get(u.userId+'/'+f.id);if(!file)return out(req,env,{error:'Arquivo indisponível.'},404);const h=cors(req,env),preview=url.searchParams.get('preview')==='1'&&f.mime!=='application/vnd.openxmlformats-officedocument.wordprocessingml.document';h.set('Content-Type',f.mime);h.set('Content-Disposition',`${preview?'inline':'attachment'}; filename*=UTF-8''${encodeURIComponent(f.name)}`);h.set('Content-Security-Policy',"sandbox; default-src 'none'");return new Response(file.body,{headers:h})}
async function filesDelete(req:Request,env:Env,url:URL){const u=await currentUser(req,env),id=url.searchParams.get('id')||'',f:any=await env.DB.prepare('SELECT * FROM files WHERE owner=? AND id=?').bind(u.userId,id).first();if(!f)return out(req,env,{error:'Arquivo não encontrado.'},404);await env.BUCKET.delete(u.userId+'/'+id);await env.DB.prepare('DELETE FROM files WHERE owner=? AND id=?').bind(u.userId,id).run();await audit(env,u.userId,u.displayName,'Documento excluído',f.name);return out(req,env,{ok:true})}

export default{async fetch(req:Request,env:Env){try{if(req.method==='OPTIONS'){checkOrigin(req,env);return new Response(null,{status:204,headers:cors(req,env)})}checkOrigin(req,env);const url=new URL(req.url),p=url.pathname;if(p==='/health')return out(req,env,{ok:true,service:'Matos Advocacia API'});if(p==='/api/auth/login'&&req.method==='POST')return login(req,env);if(p==='/api/auth/session'&&req.method==='GET')return session(req,env);if(p==='/api/auth/password'&&req.method==='POST')return changePassword(req,env);if(p==='/api/auth/logout'&&req.method==='POST')return logout(req,env);if(p==='/api/records'&&req.method==='GET')return recordsGet(req,env);if(p==='/api/records'&&req.method==='POST')return recordsPost(req,env);if(p==='/api/settings'&&req.method==='POST')return settingsPost(req,env);if(p==='/api/files'&&req.method==='POST')return filesPost(req,env,url);if(p==='/api/files'&&req.method==='GET')return filesGet(req,env,url);if(p==='/api/files'&&req.method==='DELETE')return filesDelete(req,env,url);return out(req,env,{error:'Rota não encontrada.'},404)}catch(e){return fail(req,env,e)}}};
