'use client';
import React,{useState} from 'react';
import {ArrowRight,Eye,EyeOff,LoaderCircle,LockKeyhole,ShieldCheck,UserRound} from 'lucide-react';

async function post(url:string,data:unknown){
 const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const t=await r.text();let j:any={};try{j=JSON.parse(t)}catch{}if(!r.ok)throw new Error(j.error||t||'Não foi possível concluir.');return j;
}

export default function LoginForm(){
 const [username,setUsername]=useState(''),[password,setPassword]=useState(''),[remember,setRemember]=useState(true),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{await post('/api/auth/login',{username,password,remember});location.replace('/')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <main className="auth-page"><div className="auth-shell"><div className="auth-brand"><img src="/logo.png" alt="Matos Advocacia"/></div><section className="auth-card"><span className="auth-eyebrow">PORTAL ADMINISTRATIVO</span><h1>Acesso ao Portal</h1><p className="auth-copy">Entre com seu usuário e senha para acessar os registros do escritório.</p><form onSubmit={submit} className="auth-form"><label><span>Usuário</span><div className="auth-input"><UserRound size={18}/><input value={username} onChange={e=>setUsername(e.target.value)} autoComplete="username" autoCapitalize="none" spellCheck={false} placeholder="Digite seu usuário" required/></div></label><label><span>Senha</span><div className="auth-input"><LockKeyhole size={18}/><input type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" placeholder="Digite sua senha" required/><button type="button" className="auth-eye" onClick={()=>setShow(v=>!v)} aria-label={show?'Ocultar senha':'Mostrar senha'}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label><label className="auth-remember"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/><span>Lembrar meu acesso neste dispositivo</span></label>{error&&<div className="auth-error" role="alert">{error}</div>}<button className="auth-submit" disabled={busy}>{busy?<><LoaderCircle className="auth-spin" size={18}/>Entrando...</>:<>Entrar <ArrowRight size={18}/></>}</button></form><div className="auth-secure"><ShieldCheck size={16}/><span>Acesso privado e protegido</span></div></section><p className="auth-footer">Matos Advocacia · Portal de gestão</p></div></main>;
}

export function ChangePasswordForm({username}:{username:string}){
 const [password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(e:React.FormEvent){e.preventDefault();setError('');if(password!==confirm){setError('As senhas não coincidem.');return}setBusy(true);try{await post('/api/auth/password',{password});location.reload()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <main className="auth-page"><div className="auth-shell"><div className="auth-brand"><img src="/logo.png" alt="Matos Advocacia"/></div><section className="auth-card"><span className="auth-eyebrow">PRIMEIRO ACESSO</span><h1>Crie sua nova senha</h1><p className="auth-copy">Você entrou como <strong>{username}</strong>. Por segurança, a senha provisória precisa ser substituída antes de abrir o portal.</p><form onSubmit={submit} className="auth-form"><label><span>Nova senha</span><div className="auth-input"><LockKeyhole size={18}/><input type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} autoComplete="new-password" placeholder="Mínimo de 12 caracteres" required minLength={12}/><button type="button" className="auth-eye" onClick={()=>setShow(v=>!v)} aria-label={show?'Ocultar senha':'Mostrar senha'}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label><label><span>Confirme a nova senha</span><div className="auth-input"><LockKeyhole size={18}/><input type={show?'text':'password'} value={confirm} onChange={e=>setConfirm(e.target.value)} autoComplete="new-password" placeholder="Repita a nova senha" required minLength={12}/></div></label><p className="auth-rule">Use pelo menos 12 caracteres, com letra maiúscula, minúscula e número.</p>{error&&<div className="auth-error" role="alert">{error}</div>}<button className="auth-submit" disabled={busy}>{busy?<><LoaderCircle className="auth-spin" size={18}/>Salvando...</>:<>Salvar nova senha <ArrowRight size={18}/></>}</button></form><div className="auth-secure"><ShieldCheck size={16}/><span>Depois desta etapa, a senha provisória deixa de valer.</span></div></section></div></main>;
}
